### ISSUE TITLE
Ebean-cluster should use ContainerConfig i.o. properties

### ISSUE THREAD

**Issue by rnentjes** [ebean-orm/ebean-cluster#2]
It looks like the cluster hasn't been updated after breaking changes to ebean. Atm I can't enable the cluster because the ServiceFactory.create method (in ebean-cluster) has a different signature then the ClusterBroadcastFactory one (in ebean).

Compare these 2:

https://github.com/ebean-orm/ebean/blob/master/src/main/java/io/ebeaninternal/server/cluster/ClusterBroadcastFactory.java
https://github.com/ebean-orm/ebean-cluster/blob/master/src/main/java/io/ebeaninternal/server/cluster/ServiceFactory.java

Can I expect the cluster to work, or isn't it used at all?

**Comment by rbygrave** [comment]
> Can I expect the cluster to work,

Yes.


> or isn't it used at all?

Well, it is not used if you cluster via Hazelcast or Ignite (supported distributed caches) ... and it also is not required with the 'native kubernetes clustering' via ebean-k8scache.

So we use it when we are not clustering by any of these other methods. We want a TCP sockets based cluster outside of kubernetes and not using Hazelcast / Ignite.

What happened here is updates required for ebean-k8scache broke this ebean-cluster and I have missed coming back to it and updating it as needed.
