### ISSUE TITLE
SocketClusterBroadcast register online message is missing status

### ISSUE THREAD

**Issue by rnentjes** [ebean-orm/ebean-cluster#3]
In the register method in SocketClusterBroadcast the status is not given in the message:

```java
  private void register() {
    ClusterMessage h = ClusterMessage.register(local.getHostPort(), true);
    for (int i = 0; i < members.length; i++) {
      boolean online = members[i].register(h);
      clusterLogger.info("Register as online with member [{}]", members[i].getHostPort(), online);
    }
  }
```

Looks like the log message is missing a 2nd placeholder for the online boolean. It would be nice if we could see in the log if the other cluster members are found and if they are online.

I would send a pull request but I already forked it and it has some changes I might want to send in. Not sure how you are supposed to create multiple pull requests at the same time with github.

**Comment by rbygrave** [comment]
Ok.  Are you preparing a PR?

**Comment by rnentjes** [comment]
Yes, done.

**Comment by rbygrave** [comment]
Cool - merged and released.
